/root/HuntKTm/benchmarks/multi_stream/b5/b5_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b8/b8_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b14/b14_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b15/b15_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b1/b1_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b5/b5_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b6/b6_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b8/b8_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b10/b10_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b14/b14_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b15/b15_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b5/b5_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b8/b8_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b10/b10_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b14/b14_ms_mem
/root/HuntKTm/benchmarks/multi_stream/b15/b15_ms_mem